import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Local Python environments and caches for the isolated egress gateway are
    // verified by Ruff, mypy, and pytest rather than the JavaScript linter.
    "**/.venv/**",
    "**/.pytest_cache/**",
    "**/__pycache__/**",
    // Generated by the Workflow compiler; lint the authored files in
    // src/workflows instead of generated route glue.
    "src/app/.well-known/workflow/**",
  ]),
]);

export default eslintConfig;
